# Exported from Render on 2026-08-17T17:52:55Z

version: "1"
 projects:
  - name: AS-NIP
    environments:
  - name: Production
    services:
      - type: web
        name: dns-server
        runtime: docker
        repo: https://github.com/as-nip/dns-server
        plan: free
        envVars:
        - key: DNS_SERVER_DOMAIN
          sync: false
        - key: DNS_SERVER_LOG_FOLDER_PATH
          sync: false
        region: oregon
        dockerContext: .
        dockerfilePath: ./Dockerfile
        registryCredential:
            fromRegistryCreds:
               name: Github
        domains:
        - dns.lynnl.net.eu.org
        autoDeployTrigger: commit
        renderSubdomainPolicy: disabled
